In [1]:
from pandas import read_csv

path = "iris.csv"
data = read_csv(path)

In [2]:
print(data.shape)
print()
print(data[:3])
print()
print(data.describe())
print()

(150, 5)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000



In [3]:
count_class = data.groupby('sepal_length').size()
print(count_class)
print()
correlations = data.corr(method='pearson')
print(correlations)
print()
print(data.skew())
print()

sepal_length
4.3     1
4.4     3
4.5     1
4.6     4
4.7     2
4.8     5
4.9     6
5.0    10
5.1     9
5.2     4
5.3     1
5.4     6
5.5     7
5.6     6
5.7     8
5.8     7
5.9     3
6.0     6
6.1     6
6.2     4
6.3     9
6.4     7
6.5     5
6.6     2
6.7     8
6.8     3
6.9     4
7.0     1
7.1     1
7.2     3
7.3     1
7.4     1
7.6     1
7.7     4
7.9     1
dtype: int64

              sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.109369      0.871754     0.817954
sepal_width      -0.109369     1.000000     -0.420516    -0.356544
petal_length      0.871754    -0.420516      1.000000     0.962757
petal_width       0.817954    -0.356544      0.962757     1.000000

sepal_length    0.314911
sepal_width     0.334053
petal_length   -0.274464
petal_width    -0.104997
dtype: float64



In [4]:
from sklearn import preprocessing
array = data.iloc[:, 0:4].values
print(array)
print()
data_scaler = preprocessing.MinMaxScaler(feature_range=(0,1))
data_rescaled = data_scaler.fit_transform(array)
print(data_rescaled)
print()

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

In [5]:
from sklearn.preprocessing import Binarizer
binarizer = Binarizer(threshold = 0.5).fit(array)
data_binarizer = binarizer.transform(array)
print(data_binarizer[0:5])

[[ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]]


In [6]:
print(data_binarizer)

[[ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1

In [8]:
from sklearn.preprocesing import StandardScaler

ModuleNotFoundError: No module named 'sklearn.preprocesing'

In [9]:
from sklearn.preprocesing import StandardScaler

ModuleNotFoundError: No module named 'sklearn.preprocesing'

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
import numpy as np

In [12]:
tempData = np.array([[0,0],[1,0],[0,1],[1,1]])

In [13]:
tempData_scaler = StandardScaler(tempData)

In [14]:
tempData_scaler = StandardScaler().fit(tempData)
tempData_rescaled = tempData_scaler.transform(tempData)
print(tempData_rescaled)

[[-1. -1.]
 [ 1. -1.]
 [-1.  1.]
 [ 1.  1.]]


/home/administrator/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, _DataConversionWarning)


In [15]:
data_scaler = StandardScaler().fit(array)
data_rescaled = tempData_scaler.transform(array)
print(tempData_rescaled)

ValueError: operands could not be broadcast together with shapes (150,4) (2,) (150,4) 

In [16]:
data_scaler = StandardScaler().fit(array)
data_rescaled = tempData_scaler.transform(array)
print(data_rescaled)

ValueError: operands could not be broadcast together with shapes (150,4) (2,) (150,4) 

In [17]:
data_scaler = StandardScaler().fit(array)
data_rescaled = data_scaler.transform(array)
print(tempData_rescaled)

[[-1. -1.]
 [ 1. -1.]
 [-1.  1.]
 [ 1.  1.]]


In [18]:
data_scaler = StandardScaler().fit(array)
data_rescaled = data_scaler.transform(array)
print(data_rescaled)

[[ -9.00681170e-01   1.03205722e+00  -1.34127240e+00  -1.31297673e+00]
 [ -1.14301691e+00  -1.24957601e-01  -1.34127240e+00  -1.31297673e+00]
 [ -1.38535265e+00   3.37848329e-01  -1.39813811e+00  -1.31297673e+00]
 [ -1.50652052e+00   1.06445364e-01  -1.28440670e+00  -1.31297673e+00]
 [ -1.02184904e+00   1.26346019e+00  -1.34127240e+00  -1.31297673e+00]
 [ -5.37177559e-01   1.95766909e+00  -1.17067529e+00  -1.05003079e+00]
 [ -1.50652052e+00   8.00654259e-01  -1.34127240e+00  -1.18150376e+00]
 [ -1.02184904e+00   8.00654259e-01  -1.28440670e+00  -1.31297673e+00]
 [ -1.74885626e+00  -3.56360566e-01  -1.34127240e+00  -1.31297673e+00]
 [ -1.14301691e+00   1.06445364e-01  -1.28440670e+00  -1.44444970e+00]
 [ -5.37177559e-01   1.49486315e+00  -1.28440670e+00  -1.31297673e+00]
 [ -1.26418478e+00   8.00654259e-01  -1.22754100e+00  -1.31297673e+00]
 [ -1.26418478e+00  -1.24957601e-01  -1.34127240e+00  -1.44444970e+00]
 [ -1.87002413e+00  -1.24957601e-01  -1.51186952e+00  -1.44444970e+00]
 [ -5.